# this is my first program in Python
print("Hello world!")
print("Hello again!")
print("I like typing this.")
print("This is fun.")
print("Yay! Printing.")
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print("This is my first program in Python")
print("This is my second line of code")
print("This is my third line of code")
print("This is my fourth line of code")